x-airflow-common:
  &airflow-common
  build: .
  image: heliox-airflow
  environment:
    &airflow-common-env
    PYTHONPATH: "/opt/airflow:/opt/airflow/plugins"
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY:-467473746c616e6465726973636f6f6c}
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-airflow}@postgres:5432/${POSTGRES_DB:-airflow}
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    _PIP_ADDITIONAL_REQUIREMENTS: "snowflake-connector-python pandas dbt-snowflake python-dotenv"
    SF_ACCOUNT: ${SF_ACCOUNT}
    SF_USER: ${SF_USER}
    SF_PASSWORD: ${SF_PASSWORD}
    SF_DATABASE: ${SF_DATABASE}
    SF_SCHEMA: ${SF_SCHEMA}
    SF_WAREHOUSE: ${SF_WAREHOUSE}
    SF_GOLD_LAYER: ${SF_GOLD_LAYER}
    SF_ROLE: ${SF_ROLE}
    
  volumes:
    - ./dags:/opt/airflow/dags
    - ./ingestion:/opt/airflow/ingestion
    - ./plugins:/opt/airflow/plugins
    - ./dbt_gwas_etl:/opt/airflow/dbt_gwas_etl
    - ./logs:/opt/airflow/logs
  user: "${AIRFLOW_UID:-5000}:0"
  depends_on:
    postgres:
      condition: service_healthy


services:
  postgres:
    image: postgres:13
    container_name: postgres_metastore
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-airflow}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-airflow}
      - POSTGRES_DB=${POSTGRES_DB:-airflow}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-airflow}"]
      interval: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    command: bash -c "cp -n /opt/airflow/dbt_gwas_etl/profiles.yml.example /opt/airflow/dbt_gwas_etl/profiles.yml || true && airflow version"
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_ADMIN_USER:-admin}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD:-admin}

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully