[project]
name = "genomic-disease-risk-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fsspec>=2026.3.0",
    "gcsfs>=2026.3.0",
    "numpy>=2.4.3",
    "pandas>=2.3.3",
    "pyarrow>=23.0.1",
    "python-dotenv>=1.2.2",
    "requests>=2.32.5",
    "snowflake-connector-python>=4.3.0",
    "streamlit>=1.55.0",
]
